version: "3"
services:
  postgres:
    image: postgres:15
    networks:
      - hmpps
    container_name: hmpps-workload-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=root
  localstack:
    image: localstack/localstack:3.0.2
    networks:
      - hmpps
    container_name: hmpps-workload-localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - 8999:8080
    environment:
      - SERVICES=sns,sqs
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps
    container_name: hmpps-workload-wiremock
    restart: always
    ports:
      - "8099:8099"
    command: [ "--port","8099","--global-response-templating" ]
    volumes:
      - $PWD/wiremock:/home/wiremock:rw
networks:
  hmpps:
