version: "3"
services:
  hmpps-workload:
    build:
      context: .
    container_name: hmpps-workload
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - DATABASE_ENDPOINT=postgres:5432
  postgres:
    image: postgres:11
    networks:
      - hmpps
    container_name: hmpps-workload-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=root
networks:
  hmpps:
