apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: hmpps-workload-ingress
  labels:
    app.kubernetes.io/name: hmpps-workload
    role: alert-rules
spec:
  groups:
    - name: hmpps-workload-ingress
      rules:
        - alert: 504ErrorResponses
          expr: sum(rate(nginx_ingress_controller_requests{status="504"}[5m])) > 4
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Ingress for hmpps-workload is serving 504 responses
        - alert: 5xxErrorResponses
          expr: sum(rate(nginx_ingress_controller_requests{status=~"5(0[0-3]|0[5-9]|[1-9][0-9])"}[1m])) > 0
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: Ingress for hmpps-workload is serving 500 responses
            message: Ingress serving 5x excluding 504s
        - alert: 5xxErrorResponsesOnHealthEndpoint
          expr: avg(rate(nginx_ingress_controller_requests{exported_namespace=~"hmpps-workload",ingress=~"hmpps-workload(-v1-2)",path="/health",status=~"5.*"}[5m]) > 0.5) by (ingress, exported_namespace)
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: High rate of 5xx errors on /health.
            message: Health endpoint serving errors
        - alert: RatelimitBlocking
          annotations:
            summary: Ingress is being rate limited
            message: Rate limit is being applied on ingress for hmpps-workload
          expr: avg(rate(nginx_ingress_controller_requests{exported_namespace=~"hmpps-workload",ingress=~"hmpps-workload(-v1-2)", status="429"}[1m]) > 0) by (ingress, exported_namespace)
          for: 1m
          labels:
            severity: warning
        - alert: ModSecurityBlocking
          annotations:
            summary: Mod_Security blocking ingress
            message: Mod security (406) is blocking ingress
          expr: avg(rate(nginx_ingress_controller_requests{exported_namespace=~"hmpps-workload",ingress=~"hmpps-workload(-v1-2)", status="406"}[1m]) > 0) by (ingress, exported_namespace)
          for: 1m
          labels:
            severity: warning