apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: hmpps-workload-ingress
  labels:
    app.kubernetes.io/name: hmpps-workload
    role: alert-rules
spec:
  groups:
    - name: hmpps-workload-ingress
      rules:
        # 5xx except 504 — >=3 in 5m
        - alert: WorkloadIngress5xxErrorResponses
          expr: |
            sum by (ingress, namespace) (
              increase(nginx_ingress_controller_requests{
                namespace="hmpps-workload-prod",
                ingress=~"hmpps-workload(-v1-2)?",
                status=~"5(0[0-3]|0[5-9]|[1-9][0-9])"
              }[5m])
            ) >= 3
          for: 1m
          labels: { severity: warning, service: hmpps-workload }
          annotations: { summary: Ingress serving 5xx (excl. 504) responses. }

        # Any 504s in last 5m
        - alert: WorkloadIngress504ErrorResponses
          expr: |
            sum by (ingress, namespace) (
              increase(nginx_ingress_controller_requests{
                namespace="hmpps-workload-prod",
                ingress=~"hmpps-workload(-v1-2)?",
                status="504"
              }[5m])
            ) > 0
          for: 1m
          labels: { severity: warning, service: hmpps-workload }
          annotations: { summary: Ingress serving 504 responses. }

        # 5xx on /health — sustained >0.5 req/s over 5m
        - alert: WorkloadIngress5xxOnHealthEndpoint
          expr: |
            sum by (ingress, namespace) (
              rate(nginx_ingress_controller_requests{
                namespace="hmpps-workload-prod",
                ingress=~"hmpps-workload(-v1-2)?",
                path=~"/health.*",
                status=~"5.."
              }[5m])
            ) > 0.5
          for: 5m
          labels: { severity: warning, service: hmpps-workload }
          annotations: { summary: High rate of 5xx errors on /health. }

        # 429s — any in last minute
        - alert: WorkloadIngressRatelimitBlocking
          expr: |
            sum by (ingress, namespace) (
              increase(nginx_ingress_controller_requests{
                namespace="hmpps-workload-prod",
                ingress=~"hmpps-workload(-v1-2)?",
                status="429"
              }[1m])
            ) > 0
          for: 1m
          labels: { severity: warning, service: hmpps-workload }
          annotations: { summary: Ingress is rate limiting (429s). }
