apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: hmpps-workload-notifications
  labels:
    app.kubernetes.io/name: hmpps-workload
    prometheus: cloud-platform
spec:
  groups:
    - name: hmpps-workload-notifications
      rules:
        - alert: NotificationFailedException
          expr: increase(failed_allocation_notification{type="email not send"}[5m]) > 0
          for: 0m
          labels: { severity: hmpps-workload-prod-alerts, service: hmpps-workload }
          annotations:
            description: "Email Notifications have been failing within the last 5 mins"