hmpps.sqs:
  provider: localstack
  localstackUrl: http://localhost:4566
  queues:
    hmppsallocationcompletequeue:
      queueName: hmpps_allocation_complete_event_queue
      dlqName: hmpps_allocation_complete_event_dlq
      subscribeTopicId: hmmppsdomaintopic
      subscribeFilter: '{"eventType":[ "person.community.manager.allocated", "event.manager.allocated","requirement.manager.allocated"] }'
      asyncQueueClient: true
    hmppsoffenderqueue:
      queueName: hmpps_offender_event_queue
      dlqName: hmpps_offender_event_dlq
      subscribeTopicId: hmppsoffendertopic
      subscribeFilter: '{"eventType":[ "SENTENCE_CHANGED"] }'
    tiercalcqueue:
      queueName: tier_calc_event_queue
      dlqName: tier_calc_event_dlq
      subscribeTopicId: hmmppsdomaintopic
      subscribeFilter: '{"eventType":[ "TIER_CALCULATION_COMPLETE"] }'
    hmppsauditqueue:
      accessKeyId: foobar
      secretAccessKey: foobar
      queueName: hmpps_workload_audit_queue
      asyncQueueClient: true
    workloadcalculationqueue:
      queueName: workload_calculation_event_queue
      dlqName: workload_calculation_event_dlq
      subscribeTopicId: hmmppsdomaintopic
      subscribeFilter: '{"eventType":[ "staff.available.hours.changed"] }'
    hmppsreductionscompletedqueue:
      accessKeyId: foobar
      secretAccessKey: foobar
      queueName: hmpps_reductions_completed_queue
      asyncQueueClient: true
    hmppsextractplacedqueue:
      accessKeyId: foobar
      secretAccessKey: foobar
      queueName: hmpps_extract_placed_queue
  topics:
    hmmppsdomaintopic:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}
    hmppsoffendertopic:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}

community:
  endpoint:
    url: http://localhost:8099
hmpps-tier:
  endpoint:
    url: http://localhost:8099
assess-risks-needs:
  endpoint:
    url: http://localhost:8099
ingress:
  url: localhost:8080
