hmpps.sqs:
  provider: localstack
  localstackUrl: http://localhost:4566
  queues:
    hmppsallocationcompletequeue:
      queueName: hmpps_allocation_complete_event_queue
      dlqName: hmpps_allocation_complete_event_dlq
      subscribeTopicId: hmppsdomaintopic
      subscribeFilter: '{"eventType":[ "person.community.manager.allocated", "event.manager.allocated","requirement.manager.allocated"] }'
      asyncQueueClient: true
    hmppsoffenderqueue:
      queueName: hmpps_offender_event_queue
      dlqName: hmpps_offender_event_dlq
      subscribeTopicId: hmppsoffendertopic
      subscribeFilter: '{"eventType":[ "SENTENCE_CHANGED"] }'
    tiercalcqueue:
      queueName: tier_calc_event_queue
      dlqName: tier_calc_event_dlq
      subscribeTopicId: hmppsdomaintopic
      subscribeFilter: '{"eventType":[ "TIER_CALCULATION_COMPLETE"] }'
    hmppsauditqueue:
      accessKeyId: foobar
      secretAccessKey: foobar
      queueName: hmpps_workload_audit_queue
    workloadcalculationqueue:
      queueName: workload_calculation_event_queue
      dlqName: workload_calculation_event_dlq
      subscribeTopicId: hmppsdomaintopic
      subscribeFilter: '{"eventType":[ "staff.available.hours.changed"] }'
    workloadprisonerqueue:
      queueName: workload_prisoner_queue
      dlqName: workload_prisoner_dlq
      subscribeTopicId: hmppsdomaintopic
      subscribeFilter: '{"eventType":[ "prison-offender-events.prisoner.released", "prison-offender-events.prisoner.received"] }'
    hmppsreductionscompletedqueue:
      accessKeyId: foobar
      secretAccessKey: foobar
      queueName: hmpps_reductions_completed_queue
      asyncQueueClient: true
    hmppsextractplacedqueue:
      accessKeyId: foobar
      secretAccessKey: foobar
      queueName: hmpps_extract_placed_queue
    hmppsnotificationqueue:
      accessKeyId: foobar
      secretAccessKey: foobar
      queueName: hmpps_notification_queue
      dlqName: hmpps_notification_dlq
      subscribeTopicId: hmppsdomaintopic


  topics:
    hmppsdomaintopic:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}
    hmppsoffendertopic:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}

hmpps-tier:
  endpoint:
    url: http://localhost:8099
assess-risks-needs:
  endpoint:
    url: http://localhost:8099
workforce-allocations-to-delius:
  endpoint:
    url: http://localhost:8099
ingress:
  url: localhost:8080
spring:
  datasource:
    url: "jdbc:postgresql://${database.endpoint:localhost:5432}/${database.name:postgres}"
