version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.8
  slack: circleci/slack@4.3.1

parameters:
  alerts-slack-channel:
    type: string
    default: manage_a_workforce_dev

  java-version:
    type: string
    default: 16.0
  postgres_tag:
    default: 11
    type: string

executors:
  docker-env:
    docker:
      - image: cimg/openjdk:<< pipeline.parameters.java-version >>
        environment:
          _JAVA_OPTIONS: -Xmx256m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process
      - image: postgres:<< pipeline.parameters.postgres_tag >>
        environment:
          - POSTGRES_PASSWORD=dev
          - POSTGRES_USER=root
    working_directory: ~/app


jobs:
  validate:
    executor: docker-env
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew -Dorg.gradle.jvmargs="--illegal-access=permit" -Dkotlin.daemon.jvm.options="--illegal-access=permit" check
      - slack/notify:
          event: fail
          channel: manage_a_workforce_dev
          template: basic_fail_1
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
          context: hmpps-common-vars
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - validate
            - build_docker
            - helm_lint
      - hmpps/deploy_env:
          name: deploy_dev_archive
          env: "dev_archive"
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - validate
            - build_docker
            - helm_lint
            - deploy_dev
    #      - request-preprod-approval:
    #          type: approval
    #          requires:
    #            - deploy_dev
    #      - hmpps/deploy_env:
    #          name: deploy_preprod
    #          env: "preprod"
    #          context:
    #            - hmpps-common-vars
    #            - hmpps-workload-preprod
    #          requires:
    #            - request-preprod-approval
    #      - request-prod-approval:
    #          type: approval
    #          requires:
    #            - deploy_preprod
    #      - hmpps/deploy_env:
    #          name: deploy_prod
    #          env: "prod"
    #          slack_notification: true
    #          context:
    #            - hmpps-common-vars
    #            - hmpps-workload-prod
    #          requires:
    #            - request-prod-approval

  security:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          context:
            - hmpps-common-vars
      - hmpps/veracode_policy_scan:
          context:
            - hmpps-common-vars
            - veracode-credentials


