---
generic-service:
  nameOverride: hmpps-workload

  replicaCount: 2

  image:
    repository: quay.io/hmpps/hmpps-workload
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: &ingressHost app-hostname.local    # override per environment
    tlsSecretName: hmpps-workload-cert
    contextColour: green
    v1_2_enabled: true
    v0_47_enabled: false
    annotations:
      nginx.ingress.kubernetes.io/custom-http-errors: "418"
      external-dns.alpha.kubernetes.io/aws-weight: "100"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        server_tokens off;
        location /queue-admin/** {
          deny all;
          return 401;
        }

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "stdout,logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    INGRESS_URL: *ingressHost

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-workload:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      APPLICATION_NOTIFY_KEY: "APPLICATION_NOTIFY_KEY"
    hmpps-workload-auth:
      OAUTH_CLIENT_ID: "SYSTEM_CLIENT_ID"
      OAUTH_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
    rds-live-instance-output:
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"
      DATABASE_ENDPOINT: "rds_instance_endpoint"
      DATABASE_NAME: "database_name"
    hmpps-workload-s3-extract-sqs-output:
      HMPPS_SQS_QUEUES_EXTRACTQUEUE_QUEUE_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_EXTRACTQUEUE_QUEUE_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_EXTRACTQUEUE_QUEUE_NAME: "sqs_name"
    hmpps-workload-s3-extract-sqs-dl-output:
      HMPPS_SQS_QUEUES_EXTRACTQUEUE_DLQ_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_EXTRACTQUEUE_DLQ_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_EXTRACTQUEUE_DLQ_NAME: "sqs_name"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_HMMPPSDOMAINTOPIC_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_TOPICS_HMMPPSDOMAINTOPIC_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_TOPICS_HMMPPSDOMAINTOPIC_ARN: "topic_arn"
    hmpps-workload-offender-events-sqs-instance-output:
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_QUEUE_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_QUEUE_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_QUEUE_NAME: "sqs_queue_name"
    hmpps-workload-offender-events-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_DLQ_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_DLQ_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_DLQ_NAME: "sqs_queue_name"
    hmpps-workload-tier-calc-sqs-instance-output:
      HMPPS_SQS_QUEUES_TIERCALCQUEUE_QUEUE_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_TIERCALCQUEUE_QUEUE_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_TIERCALCQUEUE_QUEUE_NAME: "sqs_queue_name"
    hmpps-workload-tier-calc-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_TIERCALCQUEUE_DLQ_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_TIERCALCQUEUE_DLQ_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_TIERCALCQUEUE_DLQ_NAME: "sqs_queue_name"
    sqs-hmpps-audit-secret:
      HMPPS_SQS_QUEUES_HMPPSAUDITQUEUE_QUEUE_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_HMPPSAUDITQUEUE_QUEUE_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_HMPPSAUDITQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-workload-calculation-queue-secret:
      HMPPS_SQS_QUEUES_WORKLOADCALCULATIONQUEUE_QUEUE_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_WORKLOADCALCULATIONQUEUE_QUEUE_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_WORKLOADCALCULATIONQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-workload-calculation-dlq-secret:
      HMPPS_SQS_QUEUES_WORKLOADCALCULATIONQUEUE_DLQ_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_WORKLOADCALCULATIONQUEUE_DLQ_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_WORKLOADCALCULATIONQUEUE_DLQ_NAME: "sqs_queue_name"


  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"
    global-protect: "35.176.93.186/32"

generic-prometheus-alerts:
  targetApplication: hmpps-workload
  alertSeverity: hmpps-tier
