# Per environment values which override defaults in hmpps-workload/values.yaml

queue_cronjob_schedule: "*/15 * * * *"

generic-service:

  ingress:
    host: &ingressHost hmpps-workload.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    OAUTH_ENDPOINT_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    HMPPS_TIER_ENDPOINT_URL: https://hmpps-tier.hmpps.service.justice.gov.uk
    INGRESS_URL: *ingressHost
    ASSESS_RISKS_NEEDS_ENDPOINT_URL: https://assess-risks-and-needs.hmpps.service.justice.gov.uk
    WORKFORCE_ALLOCATIONS_TO_DELIUS_ENDPOINT_URL: https://workforce-allocations-to-delius.hmpps.service.justice.gov.uk

  allowlist:
    delius-prod-1: 52.56.115.146/32
    delius-prod-2: 35.178.104.253/32
    delius-prod-3: 35.177.47.45/32

generic-prometheus-alerts:
  alertSeverity: hmpps-workload-prod-alerts
  rdsAlertsDatabases:
    cloud-platform-78407cd5fbd86ed5: "Workload live"
  sqsOldestAlertQueueNames:
    - "Digital-Prison-Services-prod-hmpps_workload_offender_events_queue"
    - "manage-a-workforce-production-hmpps_extract_placed_queue"
    - "manage-a-workforce-production-hmpps_reductions_completed_event_queue"
    - "manage-a-workforce-production-hmpps_workload_person_on_probation_queue"
    - "manage-a-workforce-production-hmpps_workload_prisoner_queue"
    - "manage-a-workforce-production-hmpps_workload_staff_queue"
  sqsNumberAlertQueueNames:
    - "Digital-Prison-Services-prod-hmpps_workload_offender_events_queue_dl"
    - "manage-a-workforce-production-hmpps_extract_placed_dlq"
    - "manage-a-workforce-production-hmpps_reductions_completed_event_dlq"
    - "probation-integration-prod-workforce-allocations-to-delius-dlq"
    - "manage-a-workforce-production-hmpps_workload_person_on_probation_dlq"
    - "manage-a-workforce-production-hmpps_workload_prisoner_dlq"
    - "manage-a-workforce-production-hmpps_workload_staff_dlq"
  sqsAlertsOldestThreshold: 2
  sqsAlertsTotalMessagesThreshold: 1
  runbookUrl: https://dsdmoj.atlassian.net/wiki/spaces/MaS/pages/3533964702/WMT+Run+book
  ingress5xxErrorWindowMinutes: 4

