---
# Per environment values which override defaults in hmpps-workload/values.yaml

generic-service:

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    OAUTH_ENDPOINT_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth