---
generic-service:
  nameOverride: hmpps-workload-archive
  ingress:
    host: hmpps-workload-dev-archive.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    DATABASE_NAME: hmpps_workload_archive

generic-prometheus-alerts:
  targetApplication: hmpps-workload-dev-archive


