---
# Per environment values which override defaults in hmpps-workload/values.yaml

generic-service:

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

generic-prometheus-alerts:
  targetApplication: hmpps-workload-dev


