---
# Per environment values which override defaults in hmpps-workload/values.yaml

queue_cronjob_schedule: "*/15 7-21 * * 1-5"

generic-service:

  ingress:
    host: &ingressHost hmpps-workload-dev.hmpps.service.justice.gov.uk

  replicaCount: 1
  poddisruptionbudget:
    enabled: false

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    HMPPS_TIER_ENDPOINT_URL: https://hmpps-tier-dev.hmpps.service.justice.gov.uk
    INGRESS_URL: *ingressHost
    ASSESS_RISKS_NEEDS_ENDPOINT_URL: https://assess-risks-and-needs-dev.hmpps.service.justice.gov.uk
    WORKFORCE_ALLOCATIONS_TO_DELIUS_ENDPOINT_URL: https://workforce-allocations-to-delius-dev.hmpps.service.justice.gov.uk
    HMPPS_SQS_USE_WEB_TOKEN: "true"

  allowlist:
    delius-dev-1: "35.178.19.203/32"
    delius-dev-2: "35.177.67.41/32"
    delius-dev-3: "35.178.40.151/32"
    delius-test-1: "35.176.126.163/32"
    delius-test-2: "35.178.162.73/32"
    delius-test-3: "52.56.195.113/32"

  scheduledDowntime:
    enabled: true

  namespace_secrets:
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_HMPPSDOMAINTOPIC_ARN: "topic_arn"
    hmpps-workload-offender-events-sqs-instance-output:
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_QUEUE_NAME: "sqs_queue_name"
    hmpps-workload-offender-events-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_DLQ_NAME: "sqs_queue_name"
    sqs-person-on-probation-events-secret:
      HMPPS_SQS_QUEUES_TIERCALCQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-person-on-probation-events-dl-secret:
      HMPPS_SQS_QUEUES_TIERCALCQUEUE_DLQ_NAME: "sqs_queue_name"
    sqs-hmpps-audit-secret:
      HMPPS_SQS_QUEUES_HMPPSAUDITQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-staff-events-secret:
      HMPPS_SQS_QUEUES_WORKLOADCALCULATIONQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-staff-events-dl-secret :
      HMPPS_SQS_QUEUES_WORKLOADCALCULATIONQUEUE_DLQ_NAME: "sqs_queue_name"
    hmpps-reductions-completed-sqs-instance-output:
      HMPPS_SQS_QUEUES_HMPPSREDUCTIONSCOMPLETEDQUEUE_QUEUE_NAME: "sqs_queue_name"
    hmpps-reductions-completed-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_HMPPSREDUCTIONSCOMPLETEDQUEUE_DLQ_NAME: "sqs_queue_name"
    hmpps-extract-placed-sqs-instance-output:
      HMPPS_SQS_QUEUES_HMPPSEXTRACTPLACEDQUEUE_QUEUE_NAME: "sqs_queue_name"
    hmpps-extract-placed-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_HMPPSEXTRACTPLACEDQUEUE_DLQ_NAME: "sqs_queue_name"
    sqs-prisoner-events-secret:
      HMPPS_SQS_QUEUES_WORKLOADPRISONERQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-prisoner-events-dl-secret:
      HMPPS_SQS_QUEUES_WORKLOADPRISONERQUEUE_DLQ_NAME: "sqs_queue_name"