# Per environment values which override defaults in hmpps-workload/values.yaml

queue_cronjob_schedule: "*/15 7-21 * * 1-5"

generic-service:

  ingress:
    host: &ingressHost hmpps-workload-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    OAUTH_ENDPOINT_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    HMPPS_TIER_ENDPOINT_URL: https://hmpps-tier-preprod.hmpps.service.justice.gov.uk
    INGRESS_URL: *ingressHost
    ASSESS_RISKS_NEEDS_ENDPOINT_URL: https://assess-risks-and-needs-preprod.hmpps.service.justice.gov.uk
    WORKFORCE_ALLOCATIONS_TO_DELIUS_ENDPOINT_URL: https://workforce-allocations-to-delius-preprod.hmpps.service.justice.gov.uk

  allowlist:
    delius-pre-prod-1: 52.56.240.62/32
    delius-pre-prod-2: 18.130.110.168/32
    delius-pre-prod-3: 35.178.44.184/32

  namespace_secrets:
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_HMPPSDOMAINTOPIC_ARN: "topic_arn"
    hmpps-workload-offender-events-sqs-instance-output:
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_QUEUE_NAME: "sqs_queue_name"
    hmpps-workload-offender-events-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_DLQ_NAME: "sqs_queue_name"
    sqs-person-on-probation-events-secret:
      HMPPS_SQS_QUEUES_TIERCALCQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-person-on-probation-events-dl-secret:
      HMPPS_SQS_QUEUES_TIERCALCQUEUE_DLQ_NAME: "sqs_queue_name"
    sqs-hmpps-audit-secret:
      HMPPS_SQS_QUEUES_HMPPSAUDITQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-staff-events-secret:
      HMPPS_SQS_QUEUES_WORKLOADCALCULATIONQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-staff-events-dl-secret:
      HMPPS_SQS_QUEUES_WORKLOADCALCULATIONQUEUE_DLQ_NAME: "sqs_queue_name"
    hmpps-reductions-completed-sqs-instance-output:
      HMPPS_SQS_QUEUES_HMPPSREDUCTIONSCOMPLETEDQUEUE_QUEUE_NAME: "sqs_queue_name"
    hmpps-reductions-completed-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_HMPPSREDUCTIONSCOMPLETEDQUEUE_DLQ_NAME: "sqs_queue_name"
    hmpps-extract-placed-sqs-instance-output:
      HMPPS_SQS_QUEUES_HMPPSEXTRACTPLACEDQUEUE_QUEUE_NAME: "sqs_queue_name"
    hmpps-extract-placed-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_HMPPSEXTRACTPLACEDQUEUE_DLQ_NAME: "sqs_queue_name"
    sqs-prisoner-events-secret:
      HMPPS_SQS_QUEUES_WORKLOADPRISONERQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-prisoner-events-dl-secret:
      HMPPS_SQS_QUEUES_WORKLOADPRISONERQUEUE_DLQ_NAME: "sqs_queue_name"

# Alert for business hours only - 7am to 6pm UTC (8am to 7pm BST) on week days (Monday to Friday)
generic-prometheus-alerts:
  businessHoursOnly: true