---
# Per environment values which override defaults in hmpps-workload/values.yaml

generic-service:

  ingress:
    host: hmpps-workload.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    OAUTH_ENDPOINT_URL: https://sign-in.hmpps.service.justice.gov.uk/auth