---
# Per environment values which override defaults in hmpps-workload/values.yaml

generic-service:

  ingress:
    host: &ingressHost hmpps-workload.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    OAUTH_ENDPOINT_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    COMMUNITY_ENDPOINT_URL: https://community-api-secure.probation.service.justice.gov.uk/secure
    HMPPS_TIER_ENDPOINT_URL: https://hmpps-tier.hmpps.service.justice.gov.uk
    OFFENDER_SEARCH_ENDPOINT_URL: https://probation-offender-search.hmpps.service.justice.gov.uk
    INGRESS_URL: *ingressHost
    ASSESS_RISKS_NEEDS_ENDPOINT_URL: https://assess-risks-and-needs.hmpps.service.justice.gov.uk

  allowlist:
    delius-prod-1: "52.56.115.146/32"
    delius-prod-2: "35.178.104.253/32"
    delius-prod-3: "35.177.47.45/32"