---
# Per environment values which override defaults in hmpps-workload/values.yaml

generic-service:

  ingress:
    host: hmpps-workload-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

generic-prometheus-alerts:
  targetApplication: hmpps-workload-preprod


