---
# Per environment values which override defaults in hmpps-workload/values.yaml

generic-service:

  ingress:
    host: hmpps-workload.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    OAUTH_ENDPOINT_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    COMMUNITY_ENDPOINT_URL: https://community-api-secure.probation.service.justice.gov.uk/secure
    HMPPS_TIER_ENDPOINT_URL: https://hmpps-tier.hmpps.service.justice.gov.uk