ALTER TABLE EVENT_MANAGER ADD COLUMN ALLOCATION_REASON VARCHAR NULL;
ALTER TABLE PERSON_MANAGER ADD COLUMN ALLOCATION_REASON VARCHAR NULL;
ALTER TABLE REQUIREMENT_MANAGER ADD COLUMN ALLOCATION_REASON VARCHAR NULL;

ALTER TABLE EVENT_MANAGER ALTER COLUMN ALLOCATION_REASON DROP NOT NULL;
ALTER TABLE PERSON_MANAGER ALTER COLUMN ALLOCATION_REASON DROP NOT NULL;
ALTER TABLE REQUIREMENT_MANAGER ALTER COLUMN ALLOCATION_REASON DROP NOT NULL;
