apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: wmt_migration_cronjob
spec:
  schedule: {{ .Values.cronjob_schedule }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: wmt_migration
              image: quay.io/hmpps/wmt-migration
              args:
                - /bin/bash
                - migrationRun.sh
{{ include "deployment.envs" . | nindent 14 }}
          restartPolicy: Never

